### ISSUE TITLE
package.json ver 42

### ISSUE THREAD

**Issue by maxwowpow** [Brackets-Themes/Envy#1]
It's release 41 of brackets, you put release 42 into the package.json, so it cannot be installed, have you intended to do that?

**Comment by MiguelCastillo** [comment]
@maxgrass yes because the themes in Brackets-Themes are intended to be used with the theme manager in up coming sprint 42

**Comment by MiguelCastillo** [comment]
We are working to get 42 out the door though, so it should be very soon that you will be able to install this theme along with the other ones.  Thanks for logging the issue
